# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CameraSettingsGUIDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1029, 961)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.f_load_save = QtGui.QFrame(self.centralwidget)
        self.f_load_save.setMinimumSize(QtCore.QSize(0, 49))
        self.f_load_save.setMaximumSize(QtCore.QSize(16777215, 49))
        self.f_load_save.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_load_save.setFrameShadow(QtGui.QFrame.Raised)
        self.f_load_save.setObjectName(_fromUtf8("f_load_save"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.f_load_save)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.pb_load_last = QtGui.QPushButton(self.f_load_save)
        self.pb_load_last.setEnabled(False)
        self.pb_load_last.setMinimumSize(QtCore.QSize(0, 29))
        self.pb_load_last.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pb_load_last.setObjectName(_fromUtf8("pb_load_last"))
        self.horizontalLayout_16.addWidget(self.pb_load_last)
        self.pb_load = QtGui.QPushButton(self.f_load_save)
        self.pb_load.setMinimumSize(QtCore.QSize(0, 29))
        self.pb_load.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pb_load.setObjectName(_fromUtf8("pb_load"))
        self.horizontalLayout_16.addWidget(self.pb_load)
        self.pb_save = QtGui.QPushButton(self.f_load_save)
        self.pb_save.setMinimumSize(QtCore.QSize(0, 29))
        self.pb_save.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pb_save.setObjectName(_fromUtf8("pb_save"))
        self.horizontalLayout_16.addWidget(self.pb_save)
        self.pb_apply = QtGui.QPushButton(self.f_load_save)
        self.pb_apply.setMinimumSize(QtCore.QSize(0, 29))
        self.pb_apply.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pb_apply.setObjectName(_fromUtf8("pb_apply"))
        self.horizontalLayout_16.addWidget(self.pb_apply)
        self.verticalLayout_3.addWidget(self.f_load_save)
        self.f_settings = QtGui.QFrame(self.centralwidget)
        self.f_settings.setMinimumSize(QtCore.QSize(1011, 281))
        self.f_settings.setMaximumSize(QtCore.QSize(16777215, 281))
        self.f_settings.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_settings.setFrameShadow(QtGui.QFrame.Raised)
        self.f_settings.setObjectName(_fromUtf8("f_settings"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.f_settings)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gb_general_settings = QtGui.QGroupBox(self.f_settings)
        self.gb_general_settings.setObjectName(_fromUtf8("gb_general_settings"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gb_general_settings)
        self.verticalLayout.setContentsMargins(3, 6, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.gb_general_settings)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 553, 657))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setMargin(3)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.frame_3)
        self.plainTextEdit_3.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_3.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.horizontalLayout_2.addWidget(self.plainTextEdit_3)
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rb_led_single = QtGui.QRadioButton(self.frame_4)
        self.rb_led_single.setChecked(False)
        self.rb_led_single.setObjectName(_fromUtf8("rb_led_single"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rb_led_single)
        self.horizontalLayout_3.addWidget(self.rb_led_single)
        self.rb_led_double = QtGui.QRadioButton(self.frame_4)
        self.rb_led_double.setChecked(True)
        self.rb_led_double.setObjectName(_fromUtf8("rb_led_double"))
        self.buttonGroup.addButton(self.rb_led_double)
        self.horizontalLayout_3.addWidget(self.rb_led_double)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_17 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_17.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_17.setObjectName(_fromUtf8("frame_17"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.frame_17)
        self.horizontalLayout_25.setMargin(3)
        self.horizontalLayout_25.setSpacing(3)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.plainTextEdit_11 = QtGui.QPlainTextEdit(self.frame_17)
        self.plainTextEdit_11.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_11.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_11.setObjectName(_fromUtf8("plainTextEdit_11"))
        self.horizontalLayout_25.addWidget(self.plainTextEdit_11)
        self.frame_18 = QtGui.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_18.setObjectName(_fromUtf8("frame_18"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.frame_18)
        self.horizontalLayout_26.setMargin(0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.rb_save_im_yes = QtGui.QRadioButton(self.frame_18)
        self.rb_save_im_yes.setChecked(False)
        self.rb_save_im_yes.setObjectName(_fromUtf8("rb_save_im_yes"))
        self.horizontalLayout_26.addWidget(self.rb_save_im_yes)
        self.rb_save_im_no = QtGui.QRadioButton(self.frame_18)
        self.rb_save_im_no.setChecked(True)
        self.rb_save_im_no.setObjectName(_fromUtf8("rb_save_im_no"))
        self.horizontalLayout_26.addWidget(self.rb_save_im_no)
        self.horizontalLayout_25.addWidget(self.frame_18)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_17)
        self.frame_27 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_27.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_27.setObjectName(_fromUtf8("frame_27"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout(self.frame_27)
        self.horizontalLayout_35.setMargin(3)
        self.horizontalLayout_35.setSpacing(3)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.plainTextEdit_26 = QtGui.QPlainTextEdit(self.frame_27)
        self.plainTextEdit_26.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_26.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_26.setReadOnly(True)
        self.plainTextEdit_26.setObjectName(_fromUtf8("plainTextEdit_26"))
        self.horizontalLayout_35.addWidget(self.plainTextEdit_26)
        self.frame_28 = QtGui.QFrame(self.frame_27)
        self.frame_28.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_28.setObjectName(_fromUtf8("frame_28"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout(self.frame_28)
        self.horizontalLayout_36.setMargin(0)
        self.horizontalLayout_36.setSpacing(3)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.plainTextEdit_27 = QtGui.QPlainTextEdit(self.frame_28)
        self.plainTextEdit_27.setMinimumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_27.setMaximumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_27.setObjectName(_fromUtf8("plainTextEdit_27"))
        self.horizontalLayout_36.addWidget(self.plainTextEdit_27)
        self.pt_arena_size_x = QtGui.QPlainTextEdit(self.frame_28)
        self.pt_arena_size_x.setMinimumSize(QtCore.QSize(0, 28))
        self.pt_arena_size_x.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_arena_size_x.setObjectName(_fromUtf8("pt_arena_size_x"))
        self.horizontalLayout_36.addWidget(self.pt_arena_size_x)
        self.plainTextEdit_29 = QtGui.QPlainTextEdit(self.frame_28)
        self.plainTextEdit_29.setMinimumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_29.setMaximumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_29.setObjectName(_fromUtf8("plainTextEdit_29"))
        self.horizontalLayout_36.addWidget(self.plainTextEdit_29)
        self.pt_arena_size_y = QtGui.QPlainTextEdit(self.frame_28)
        self.pt_arena_size_y.setMinimumSize(QtCore.QSize(0, 28))
        self.pt_arena_size_y.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_arena_size_y.setObjectName(_fromUtf8("pt_arena_size_y"))
        self.horizontalLayout_36.addWidget(self.pt_arena_size_y)
        self.horizontalLayout_35.addWidget(self.frame_28)
        self.horizontalLayout_35.setStretch(0, 1)
        self.horizontalLayout_35.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_27)
        self.frame_25 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_25.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_25.setObjectName(_fromUtf8("frame_25"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.frame_25)
        self.horizontalLayout_33.setMargin(3)
        self.horizontalLayout_33.setSpacing(3)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.plainTextEdit_14 = QtGui.QPlainTextEdit(self.frame_25)
        self.plainTextEdit_14.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_14.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_14.setReadOnly(True)
        self.plainTextEdit_14.setObjectName(_fromUtf8("plainTextEdit_14"))
        self.horizontalLayout_33.addWidget(self.plainTextEdit_14)
        self.frame_26 = QtGui.QFrame(self.frame_25)
        self.frame_26.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_26.setObjectName(_fromUtf8("frame_26"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout(self.frame_26)
        self.horizontalLayout_34.setMargin(0)
        self.horizontalLayout_34.setSpacing(3)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.plainTextEdit_24 = QtGui.QPlainTextEdit(self.frame_26)
        self.plainTextEdit_24.setMinimumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_24.setMaximumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_24.setObjectName(_fromUtf8("plainTextEdit_24"))
        self.horizontalLayout_34.addWidget(self.plainTextEdit_24)
        self.pt_nsquares_x = QtGui.QPlainTextEdit(self.frame_26)
        self.pt_nsquares_x.setMinimumSize(QtCore.QSize(0, 28))
        self.pt_nsquares_x.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_nsquares_x.setObjectName(_fromUtf8("pt_nsquares_x"))
        self.horizontalLayout_34.addWidget(self.pt_nsquares_x)
        self.plainTextEdit_25 = QtGui.QPlainTextEdit(self.frame_26)
        self.plainTextEdit_25.setMinimumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_25.setMaximumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_25.setObjectName(_fromUtf8("plainTextEdit_25"))
        self.horizontalLayout_34.addWidget(self.plainTextEdit_25)
        self.pt_nsquares_y = QtGui.QPlainTextEdit(self.frame_26)
        self.pt_nsquares_y.setMinimumSize(QtCore.QSize(0, 28))
        self.pt_nsquares_y.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_nsquares_y.setObjectName(_fromUtf8("pt_nsquares_y"))
        self.horizontalLayout_34.addWidget(self.pt_nsquares_y)
        self.horizontalLayout_33.addWidget(self.frame_26)
        self.horizontalLayout_33.setStretch(0, 1)
        self.horizontalLayout_33.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_25)
        self.frame_24 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_24.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_24.setObjectName(_fromUtf8("frame_24"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.frame_24)
        self.horizontalLayout_31.setMargin(3)
        self.horizontalLayout_31.setSpacing(3)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.plainTextEdit_13 = QtGui.QPlainTextEdit(self.frame_24)
        self.plainTextEdit_13.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_13.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_13.setReadOnly(True)
        self.plainTextEdit_13.setObjectName(_fromUtf8("plainTextEdit_13"))
        self.horizontalLayout_31.addWidget(self.plainTextEdit_13)
        self.frame = QtGui.QFrame(self.frame_24)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_32.setMargin(0)
        self.horizontalLayout_32.setSpacing(3)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(24, 28))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(24, 28))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.horizontalLayout_32.addWidget(self.plainTextEdit)
        self.pt_offset_x = QtGui.QPlainTextEdit(self.frame)
        self.pt_offset_x.setMinimumSize(QtCore.QSize(0, 28))
        self.pt_offset_x.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_offset_x.setObjectName(_fromUtf8("pt_offset_x"))
        self.horizontalLayout_32.addWidget(self.pt_offset_x)
        self.plainTextEdit_23 = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit_23.setMinimumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_23.setMaximumSize(QtCore.QSize(24, 28))
        self.plainTextEdit_23.setObjectName(_fromUtf8("plainTextEdit_23"))
        self.horizontalLayout_32.addWidget(self.plainTextEdit_23)
        self.pt_offset_y = QtGui.QPlainTextEdit(self.frame)
        self.pt_offset_y.setMinimumSize(QtCore.QSize(0, 28))
        self.pt_offset_y.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_offset_y.setObjectName(_fromUtf8("pt_offset_y"))
        self.horizontalLayout_32.addWidget(self.pt_offset_y)
        self.horizontalLayout_31.addWidget(self.frame)
        self.horizontalLayout_31.setStretch(0, 1)
        self.horizontalLayout_31.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_24)
        self.frame_16 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.frame_16)
        self.horizontalLayout_19.setMargin(3)
        self.horizontalLayout_19.setSpacing(3)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.plainTextEdit_9 = QtGui.QPlainTextEdit(self.frame_16)
        self.plainTextEdit_9.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_9.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_9.setReadOnly(True)
        self.plainTextEdit_9.setObjectName(_fromUtf8("plainTextEdit_9"))
        self.horizontalLayout_19.addWidget(self.plainTextEdit_9)
        self.pt_calibration_square = QtGui.QPlainTextEdit(self.frame_16)
        self.pt_calibration_square.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_calibration_square.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_calibration_square.setReadOnly(False)
        self.pt_calibration_square.setObjectName(_fromUtf8("pt_calibration_square"))
        self.horizontalLayout_19.addWidget(self.pt_calibration_square)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_16)
        self.frame_6 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setMargin(3)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.plainTextEdit_6 = QtGui.QPlainTextEdit(self.frame_6)
        self.plainTextEdit_6.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_6.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_6.setReadOnly(True)
        self.plainTextEdit_6.setObjectName(_fromUtf8("plainTextEdit_6"))
        self.horizontalLayout_5.addWidget(self.plainTextEdit_6)
        self.pt_smooth_r = QtGui.QPlainTextEdit(self.frame_6)
        self.pt_smooth_r.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_smooth_r.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_smooth_r.setReadOnly(False)
        self.pt_smooth_r.setObjectName(_fromUtf8("pt_smooth_r"))
        self.horizontalLayout_5.addWidget(self.pt_smooth_r)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_15 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_15)
        self.horizontalLayout_12.setMargin(3)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.plainTextEdit_30 = QtGui.QPlainTextEdit(self.frame_15)
        self.plainTextEdit_30.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_30.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_30.setReadOnly(True)
        self.plainTextEdit_30.setObjectName(_fromUtf8("plainTextEdit_30"))
        self.horizontalLayout_12.addWidget(self.plainTextEdit_30)
        self.pt_LED_separation = QtGui.QPlainTextEdit(self.frame_15)
        self.pt_LED_separation.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_LED_separation.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_LED_separation.setReadOnly(False)
        self.pt_LED_separation.setObjectName(_fromUtf8("pt_LED_separation"))
        self.horizontalLayout_12.addWidget(self.pt_LED_separation)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_15)
        self.frame_14 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frame_14)
        self.horizontalLayout_11.setMargin(3)
        self.horizontalLayout_11.setSpacing(3)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.plainTextEdit_7 = QtGui.QPlainTextEdit(self.frame_14)
        self.plainTextEdit_7.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_7.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_7.setReadOnly(True)
        self.plainTextEdit_7.setObjectName(_fromUtf8("plainTextEdit_7"))
        self.horizontalLayout_11.addWidget(self.plainTextEdit_7)
        self.pt_LED_angle = QtGui.QPlainTextEdit(self.frame_14)
        self.pt_LED_angle.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_LED_angle.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_LED_angle.setReadOnly(False)
        self.pt_LED_angle.setObjectName(_fromUtf8("pt_LED_angle"))
        self.horizontalLayout_11.addWidget(self.pt_LED_angle)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_14)
        self.frame_20 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_20.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_20.setObjectName(_fromUtf8("frame_20"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.frame_20)
        self.horizontalLayout_28.setMargin(3)
        self.horizontalLayout_28.setSpacing(3)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.plainTextEdit_16 = QtGui.QPlainTextEdit(self.frame_20)
        self.plainTextEdit_16.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_16.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_16.setReadOnly(True)
        self.plainTextEdit_16.setObjectName(_fromUtf8("plainTextEdit_16"))
        self.horizontalLayout_28.addWidget(self.plainTextEdit_16)
        self.pt_camera_iso = QtGui.QPlainTextEdit(self.frame_20)
        self.pt_camera_iso.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_camera_iso.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_camera_iso.setReadOnly(False)
        self.pt_camera_iso.setObjectName(_fromUtf8("pt_camera_iso"))
        self.horizontalLayout_28.addWidget(self.pt_camera_iso)
        self.horizontalLayout_28.setStretch(0, 1)
        self.horizontalLayout_28.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_20)
        self.frame_19 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_19.setObjectName(_fromUtf8("frame_19"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.frame_19)
        self.horizontalLayout_27.setMargin(3)
        self.horizontalLayout_27.setSpacing(3)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.plainTextEdit_15 = QtGui.QPlainTextEdit(self.frame_19)
        self.plainTextEdit_15.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_15.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_15.setReadOnly(True)
        self.plainTextEdit_15.setObjectName(_fromUtf8("plainTextEdit_15"))
        self.horizontalLayout_27.addWidget(self.plainTextEdit_15)
        self.pt_shutter_speed = QtGui.QPlainTextEdit(self.frame_19)
        self.pt_shutter_speed.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_shutter_speed.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_shutter_speed.setReadOnly(False)
        self.pt_shutter_speed.setObjectName(_fromUtf8("pt_shutter_speed"))
        self.horizontalLayout_27.addWidget(self.pt_shutter_speed)
        self.horizontalLayout_27.setStretch(0, 1)
        self.horizontalLayout_27.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_19)
        self.frame_21 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 39))
        self.frame_21.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_21.setObjectName(_fromUtf8("frame_21"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.frame_21)
        self.horizontalLayout_29.setMargin(3)
        self.horizontalLayout_29.setSpacing(3)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.plainTextEdit_17 = QtGui.QPlainTextEdit(self.frame_21)
        self.plainTextEdit_17.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_17.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_17.setReadOnly(True)
        self.plainTextEdit_17.setObjectName(_fromUtf8("plainTextEdit_17"))
        self.horizontalLayout_29.addWidget(self.plainTextEdit_17)
        self.lw_exposure_settings = QtGui.QListWidget(self.frame_21)
        self.lw_exposure_settings.setObjectName(_fromUtf8("lw_exposure_settings"))
        self.horizontalLayout_29.addWidget(self.lw_exposure_settings)
        self.verticalLayout_4.addWidget(self.frame_21)
        self.frame_5 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setMargin(3)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.frame_5)
        self.plainTextEdit_4.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_4.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.horizontalLayout_4.addWidget(self.plainTextEdit_4)
        self.pt_resolution = QtGui.QPlainTextEdit(self.frame_5)
        self.pt_resolution.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_resolution.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_resolution.setReadOnly(False)
        self.pt_resolution.setObjectName(_fromUtf8("pt_resolution"))
        self.horizontalLayout_4.addWidget(self.pt_resolution)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.frame_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.frame_2)
        self.plainTextEdit_2.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.horizontalLayout.addWidget(self.plainTextEdit_2)
        self.pt_local_ip = QtGui.QPlainTextEdit(self.frame_2)
        self.pt_local_ip.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_local_ip.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_local_ip.setReadOnly(False)
        self.pt_local_ip.setObjectName(_fromUtf8("pt_local_ip"))
        self.horizontalLayout.addWidget(self.pt_local_ip)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_8 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setMargin(3)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.plainTextEdit_10 = QtGui.QPlainTextEdit(self.frame_8)
        self.plainTextEdit_10.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_10.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_10.setReadOnly(True)
        self.plainTextEdit_10.setObjectName(_fromUtf8("plainTextEdit_10"))
        self.horizontalLayout_7.addWidget(self.plainTextEdit_10)
        self.pt_rpi_password = QtGui.QPlainTextEdit(self.frame_8)
        self.pt_rpi_password.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_rpi_password.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_rpi_password.setReadOnly(False)
        self.pt_rpi_password.setObjectName(_fromUtf8("pt_rpi_password"))
        self.horizontalLayout_7.addWidget(self.pt_rpi_password)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_7 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setMargin(3)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.plainTextEdit_8 = QtGui.QPlainTextEdit(self.frame_7)
        self.plainTextEdit_8.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_8.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_8.setReadOnly(True)
        self.plainTextEdit_8.setObjectName(_fromUtf8("plainTextEdit_8"))
        self.horizontalLayout_6.addWidget(self.plainTextEdit_8)
        self.pt_rpi_username = QtGui.QPlainTextEdit(self.frame_7)
        self.pt_rpi_username.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_rpi_username.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_rpi_username.setReadOnly(False)
        self.pt_rpi_username.setObjectName(_fromUtf8("pt_rpi_username"))
        self.horizontalLayout_6.addWidget(self.pt_rpi_username)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_23 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_23.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_23.setObjectName(_fromUtf8("frame_23"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.frame_23)
        self.horizontalLayout_30.setMargin(3)
        self.horizontalLayout_30.setSpacing(3)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.plainTextEdit_22 = QtGui.QPlainTextEdit(self.frame_23)
        self.plainTextEdit_22.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_22.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_22.setReadOnly(True)
        self.plainTextEdit_22.setObjectName(_fromUtf8("plainTextEdit_22"))
        self.horizontalLayout_30.addWidget(self.plainTextEdit_22)
        self.pt_posport = QtGui.QPlainTextEdit(self.frame_23)
        self.pt_posport.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_posport.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_posport.setReadOnly(False)
        self.pt_posport.setObjectName(_fromUtf8("pt_posport"))
        self.horizontalLayout_30.addWidget(self.pt_posport)
        self.horizontalLayout_30.setStretch(0, 1)
        self.horizontalLayout_30.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_23)
        self.frame_22 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_22.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_22.setObjectName(_fromUtf8("frame_22"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.frame_22)
        self.horizontalLayout_17.setMargin(3)
        self.horizontalLayout_17.setSpacing(3)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.plainTextEdit_21 = QtGui.QPlainTextEdit(self.frame_22)
        self.plainTextEdit_21.setMinimumSize(QtCore.QSize(180, 28))
        self.plainTextEdit_21.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_21.setReadOnly(True)
        self.plainTextEdit_21.setObjectName(_fromUtf8("plainTextEdit_21"))
        self.horizontalLayout_17.addWidget(self.plainTextEdit_21)
        self.pt_stopport = QtGui.QPlainTextEdit(self.frame_22)
        self.pt_stopport.setMinimumSize(QtCore.QSize(180, 28))
        self.pt_stopport.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_stopport.setReadOnly(False)
        self.pt_stopport.setObjectName(_fromUtf8("pt_stopport"))
        self.horizontalLayout_17.addWidget(self.pt_stopport)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_22)
        self.frame_7.raise_()
        self.frame_3.raise_()
        self.frame_8.raise_()
        self.frame_5.raise_()
        self.frame_19.raise_()
        self.frame_20.raise_()
        self.frame_21.raise_()
        self.frame_2.raise_()
        self.frame_22.raise_()
        self.frame_23.raise_()
        self.frame_17.raise_()
        self.frame_16.raise_()
        self.frame_25.raise_()
        self.frame_24.raise_()
        self.frame_27.raise_()
        self.frame_14.raise_()
        self.frame_15.raise_()
        self.frame_6.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_10.addWidget(self.gb_general_settings)
        self.gb_individual_settings = QtGui.QGroupBox(self.f_settings)
        self.gb_individual_settings.setObjectName(_fromUtf8("gb_individual_settings"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gb_individual_settings)
        self.verticalLayout_5.setContentsMargins(3, 6, 3, 3)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea_2 = QtGui.QScrollArea(self.gb_individual_settings)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(220, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 218, 232))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.setMargin(3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_9 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setMargin(3)
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.plainTextEdit_19 = QtGui.QPlainTextEdit(self.frame_9)
        self.plainTextEdit_19.setMinimumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_19.setMaximumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_19.setReadOnly(True)
        self.plainTextEdit_19.setObjectName(_fromUtf8("plainTextEdit_19"))
        self.horizontalLayout_8.addWidget(self.plainTextEdit_19)
        self.plainTextEdit_20 = QtGui.QPlainTextEdit(self.frame_9)
        self.plainTextEdit_20.setMinimumSize(QtCore.QSize(45, 28))
        self.plainTextEdit_20.setMaximumSize(QtCore.QSize(50, 28))
        self.plainTextEdit_20.setReadOnly(True)
        self.plainTextEdit_20.setObjectName(_fromUtf8("plainTextEdit_20"))
        self.horizontalLayout_8.addWidget(self.plainTextEdit_20)
        self.plainTextEdit_12 = QtGui.QPlainTextEdit(self.frame_9)
        self.plainTextEdit_12.setMinimumSize(QtCore.QSize(100, 28))
        self.plainTextEdit_12.setMaximumSize(QtCore.QSize(16777215, 28))
        self.plainTextEdit_12.setReadOnly(True)
        self.plainTextEdit_12.setObjectName(_fromUtf8("plainTextEdit_12"))
        self.horizontalLayout_8.addWidget(self.plainTextEdit_12)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_10 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setMargin(3)
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.plainTextEdit_18 = QtGui.QPlainTextEdit(self.frame_10)
        self.plainTextEdit_18.setMinimumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_18.setMaximumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_18.setReadOnly(True)
        self.plainTextEdit_18.setObjectName(_fromUtf8("plainTextEdit_18"))
        self.horizontalLayout_9.addWidget(self.plainTextEdit_18)
        self.cb_rpi_1 = QtGui.QCheckBox(self.frame_10)
        self.cb_rpi_1.setMinimumSize(QtCore.QSize(50, 0))
        self.cb_rpi_1.setText(_fromUtf8(""))
        self.cb_rpi_1.setObjectName(_fromUtf8("cb_rpi_1"))
        self.horizontalLayout_9.addWidget(self.cb_rpi_1)
        self.pt_rpi_ip_1 = QtGui.QPlainTextEdit(self.frame_10)
        self.pt_rpi_ip_1.setMinimumSize(QtCore.QSize(100, 28))
        self.pt_rpi_ip_1.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_rpi_ip_1.setReadOnly(False)
        self.pt_rpi_ip_1.setObjectName(_fromUtf8("pt_rpi_ip_1"))
        self.horizontalLayout_9.addWidget(self.pt_rpi_ip_1)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_11 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_11)
        self.horizontalLayout_13.setMargin(3)
        self.horizontalLayout_13.setSpacing(3)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.plainTextEdit_28 = QtGui.QPlainTextEdit(self.frame_11)
        self.plainTextEdit_28.setMinimumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_28.setMaximumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_28.setReadOnly(True)
        self.plainTextEdit_28.setObjectName(_fromUtf8("plainTextEdit_28"))
        self.horizontalLayout_13.addWidget(self.plainTextEdit_28)
        self.cb_rpi_2 = QtGui.QCheckBox(self.frame_11)
        self.cb_rpi_2.setMinimumSize(QtCore.QSize(50, 0))
        self.cb_rpi_2.setText(_fromUtf8(""))
        self.cb_rpi_2.setObjectName(_fromUtf8("cb_rpi_2"))
        self.horizontalLayout_13.addWidget(self.cb_rpi_2)
        self.pt_rpi_ip_2 = QtGui.QPlainTextEdit(self.frame_11)
        self.pt_rpi_ip_2.setMinimumSize(QtCore.QSize(100, 28))
        self.pt_rpi_ip_2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_rpi_ip_2.setReadOnly(False)
        self.pt_rpi_ip_2.setObjectName(_fromUtf8("pt_rpi_ip_2"))
        self.horizontalLayout_13.addWidget(self.pt_rpi_ip_2)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_12 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.frame_12)
        self.horizontalLayout_14.setMargin(3)
        self.horizontalLayout_14.setSpacing(3)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.plainTextEdit_32 = QtGui.QPlainTextEdit(self.frame_12)
        self.plainTextEdit_32.setMinimumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_32.setMaximumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_32.setReadOnly(True)
        self.plainTextEdit_32.setObjectName(_fromUtf8("plainTextEdit_32"))
        self.horizontalLayout_14.addWidget(self.plainTextEdit_32)
        self.cb_rpi_3 = QtGui.QCheckBox(self.frame_12)
        self.cb_rpi_3.setMinimumSize(QtCore.QSize(50, 0))
        self.cb_rpi_3.setText(_fromUtf8(""))
        self.cb_rpi_3.setObjectName(_fromUtf8("cb_rpi_3"))
        self.horizontalLayout_14.addWidget(self.cb_rpi_3)
        self.pt_rpi_ip_3 = QtGui.QPlainTextEdit(self.frame_12)
        self.pt_rpi_ip_3.setMinimumSize(QtCore.QSize(100, 28))
        self.pt_rpi_ip_3.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_rpi_ip_3.setReadOnly(False)
        self.pt_rpi_ip_3.setObjectName(_fromUtf8("pt_rpi_ip_3"))
        self.horizontalLayout_14.addWidget(self.pt_rpi_ip_3)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_13 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.frame_13)
        self.horizontalLayout_15.setMargin(3)
        self.horizontalLayout_15.setSpacing(3)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.plainTextEdit_36 = QtGui.QPlainTextEdit(self.frame_13)
        self.plainTextEdit_36.setMinimumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_36.setMaximumSize(QtCore.QSize(28, 28))
        self.plainTextEdit_36.setReadOnly(True)
        self.plainTextEdit_36.setObjectName(_fromUtf8("plainTextEdit_36"))
        self.horizontalLayout_15.addWidget(self.plainTextEdit_36)
        self.cb_rpi_4 = QtGui.QCheckBox(self.frame_13)
        self.cb_rpi_4.setMinimumSize(QtCore.QSize(50, 0))
        self.cb_rpi_4.setText(_fromUtf8(""))
        self.cb_rpi_4.setObjectName(_fromUtf8("cb_rpi_4"))
        self.horizontalLayout_15.addWidget(self.cb_rpi_4)
        self.pt_rpi_ip_4 = QtGui.QPlainTextEdit(self.frame_13)
        self.pt_rpi_ip_4.setMinimumSize(QtCore.QSize(100, 28))
        self.pt_rpi_ip_4.setMaximumSize(QtCore.QSize(16777215, 28))
        self.pt_rpi_ip_4.setReadOnly(False)
        self.pt_rpi_ip_4.setObjectName(_fromUtf8("pt_rpi_ip_4"))
        self.horizontalLayout_15.addWidget(self.pt_rpi_ip_4)
        self.verticalLayout_2.addWidget(self.frame_13)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.horizontalLayout_10.addWidget(self.gb_individual_settings)
        self.f_calibration = QtGui.QFrame(self.f_settings)
        self.f_calibration.setMinimumSize(QtCore.QSize(160, 0))
        self.f_calibration.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.f_calibration.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_calibration.setFrameShadow(QtGui.QFrame.Raised)
        self.f_calibration.setObjectName(_fromUtf8("f_calibration"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.f_calibration)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pb_show_image = QtGui.QPushButton(self.f_calibration)
        self.pb_show_image.setMinimumSize(QtCore.QSize(101, 29))
        self.pb_show_image.setObjectName(_fromUtf8("pb_show_image"))
        self.verticalLayout_6.addWidget(self.pb_show_image)
        self.pb_calibrate = QtGui.QPushButton(self.f_calibration)
        self.pb_calibrate.setMinimumSize(QtCore.QSize(101, 29))
        self.pb_calibrate.setObjectName(_fromUtf8("pb_calibrate"))
        self.verticalLayout_6.addWidget(self.pb_calibrate)
        self.pb_show_calibration = QtGui.QPushButton(self.f_calibration)
        self.pb_show_calibration.setMinimumSize(QtCore.QSize(101, 29))
        self.pb_show_calibration.setObjectName(_fromUtf8("pb_show_calibration"))
        self.verticalLayout_6.addWidget(self.pb_show_calibration)
        self.pb_overlay_calibration = QtGui.QPushButton(self.f_calibration)
        self.pb_overlay_calibration.setMinimumSize(QtCore.QSize(101, 29))
        self.pb_overlay_calibration.setObjectName(_fromUtf8("pb_overlay_calibration"))
        self.verticalLayout_6.addWidget(self.pb_overlay_calibration)
        self.pb_test_tracking = QtGui.QPushButton(self.f_calibration)
        self.pb_test_tracking.setMinimumSize(QtCore.QSize(101, 29))
        self.pb_test_tracking.setObjectName(_fromUtf8("pb_test_tracking"))
        self.verticalLayout_6.addWidget(self.pb_test_tracking)
        self.horizontalLayout_10.addWidget(self.f_calibration)
        self.verticalLayout_3.addWidget(self.f_settings)
        self.f_plots = QtGui.QFrame(self.centralwidget)
        self.f_plots.setMinimumSize(QtCore.QSize(920, 499))
        self.f_plots.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_plots.setFrameShadow(QtGui.QFrame.Raised)
        self.f_plots.setObjectName(_fromUtf8("f_plots"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.f_plots)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.sa_plots = QtGui.QScrollArea(self.f_plots)
        self.sa_plots.setMinimumSize(QtCore.QSize(900, 350))
        self.sa_plots.setWidgetResizable(True)
        self.sa_plots.setObjectName(_fromUtf8("sa_plots"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 3340, 516))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.im_view_1 = GraphicsLayoutWidget(self.groupBox)
        self.im_view_1.setMinimumSize(QtCore.QSize(800, 400))
        self.im_view_1.setObjectName(_fromUtf8("im_view_1"))
        self.horizontalLayout_20.addWidget(self.im_view_1)
        self.horizontalLayout_24.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.im_view_2 = GraphicsLayoutWidget(self.groupBox_2)
        self.im_view_2.setMinimumSize(QtCore.QSize(800, 400))
        self.im_view_2.setObjectName(_fromUtf8("im_view_2"))
        self.horizontalLayout_21.addWidget(self.im_view_2)
        self.horizontalLayout_24.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.im_view_3 = GraphicsLayoutWidget(self.groupBox_3)
        self.im_view_3.setMinimumSize(QtCore.QSize(800, 400))
        self.im_view_3.setObjectName(_fromUtf8("im_view_3"))
        self.horizontalLayout_22.addWidget(self.im_view_3)
        self.horizontalLayout_24.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.im_view_4 = GraphicsLayoutWidget(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.im_view_4.sizePolicy().hasHeightForWidth())
        self.im_view_4.setSizePolicy(sizePolicy)
        self.im_view_4.setMinimumSize(QtCore.QSize(800, 400))
        self.im_view_4.setObjectName(_fromUtf8("im_view_4"))
        self.horizontalLayout_23.addWidget(self.im_view_4)
        self.horizontalLayout_24.addWidget(self.groupBox_4)
        self.sa_plots.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_18.addWidget(self.sa_plots)
        self.verticalLayout_3.addWidget(self.f_plots)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.lw_exposure_settings.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Camera Settings", None))
        self.pb_load_last.setText(_translate("MainWindow", "Load Last", None))
        self.pb_load.setText(_translate("MainWindow", "Load", None))
        self.pb_save.setText(_translate("MainWindow", "Save", None))
        self.pb_apply.setText(_translate("MainWindow", "Apply", None))
        self.gb_general_settings.setTitle(_translate("MainWindow", "General Settings", None))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "LED mode:", None))
        self.rb_led_single.setText(_translate("MainWindow", "Single", None))
        self.rb_led_double.setText(_translate("MainWindow", "Double", None))
        self.plainTextEdit_11.setPlainText(_translate("MainWindow", "Save frames to images?", None))
        self.rb_save_im_yes.setText(_translate("MainWindow", "Yes", None))
        self.rb_save_im_no.setText(_translate("MainWindow", "No", None))
        self.plainTextEdit_26.setPlainText(_translate("MainWindow", "Arena size (cm):", None))
        self.plainTextEdit_27.setPlainText(_translate("MainWindow", "X:", None))
        self.pt_arena_size_x.setPlainText(_translate("MainWindow", "140", None))
        self.plainTextEdit_29.setPlainText(_translate("MainWindow", "Y:", None))
        self.pt_arena_size_y.setPlainText(_translate("MainWindow", "100", None))
        self.plainTextEdit_14.setPlainText(_translate("MainWindow", "Calibration squares (n):", None))
        self.plainTextEdit_24.setPlainText(_translate("MainWindow", "X:", None))
        self.pt_nsquares_x.setPlainText(_translate("MainWindow", "12", None))
        self.plainTextEdit_25.setPlainText(_translate("MainWindow", "Y:", None))
        self.pt_nsquares_y.setPlainText(_translate("MainWindow", "8", None))
        self.plainTextEdit_13.setPlainText(_translate("MainWindow", "Corner offset (cm):", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "X:", None))
        self.pt_offset_x.setPlainText(_translate("MainWindow", "5", None))
        self.plainTextEdit_23.setPlainText(_translate("MainWindow", "Y:", None))
        self.pt_offset_y.setPlainText(_translate("MainWindow", "5", None))
        self.plainTextEdit_9.setPlainText(_translate("MainWindow", "Calibration Square Side (cm):", None))
        self.pt_calibration_square.setPlainText(_translate("MainWindow", "10", None))
        self.plainTextEdit_6.setPlainText(_translate("MainWindow", "Smoothing radius (pixels):", None))
        self.pt_smooth_r.setPlainText(_translate("MainWindow", "3", None))
        self.plainTextEdit_30.setPlainText(_translate("MainWindow", "LED separation (cm):", None))
        self.pt_LED_separation.setPlainText(_translate("MainWindow", "5", None))
        self.plainTextEdit_7.setPlainText(_translate("MainWindow", "LED angle (degrees):", None))
        self.pt_LED_angle.setPlainText(_translate("MainWindow", "5", None))
        self.plainTextEdit_16.setPlainText(_translate("MainWindow", "CameraISO (0=auto - 800):", None))
        self.pt_camera_iso.setPlainText(_translate("MainWindow", "0", None))
        self.plainTextEdit_15.setPlainText(_translate("MainWindow", "Shutter Speed (microseconds):", None))
        self.pt_shutter_speed.setPlainText(_translate("MainWindow", "0", None))
        self.plainTextEdit_17.setPlainText(_translate("MainWindow", "Exposure Setting:", None))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "Resolution:", None))
        self.pt_resolution.setPlainText(_translate("MainWindow", "800, 608", None))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "Local IP:", None))
        self.pt_local_ip.setPlainText(_translate("MainWindow", "10.0.0.10", None))
        self.plainTextEdit_10.setPlainText(_translate("MainWindow", "RPi password:", None))
        self.pt_rpi_password.setPlainText(_translate("MainWindow", "raspberry", None))
        self.plainTextEdit_8.setPlainText(_translate("MainWindow", "RPi username:", None))
        self.pt_rpi_username.setPlainText(_translate("MainWindow", "pi", None))
        self.plainTextEdit_22.setPlainText(_translate("MainWindow", "Position Port:", None))
        self.pt_posport.setPlainText(_translate("MainWindow", "5600", None))
        self.plainTextEdit_21.setPlainText(_translate("MainWindow", "Stop Port:", None))
        self.pt_stopport.setPlainText(_translate("MainWindow", "5601", None))
        self.gb_individual_settings.setTitle(_translate("MainWindow", "Individual Cameras", None))
        self.plainTextEdit_19.setPlainText(_translate("MainWindow", "Nr", None))
        self.plainTextEdit_20.setPlainText(_translate("MainWindow", "Use?", None))
        self.plainTextEdit_12.setPlainText(_translate("MainWindow", "IP address", None))
        self.plainTextEdit_18.setPlainText(_translate("MainWindow", "1", None))
        self.pt_rpi_ip_1.setPlainText(_translate("MainWindow", "10.0.0.20", None))
        self.plainTextEdit_28.setPlainText(_translate("MainWindow", "2", None))
        self.pt_rpi_ip_2.setPlainText(_translate("MainWindow", "10.0.0.21", None))
        self.plainTextEdit_32.setPlainText(_translate("MainWindow", "3", None))
        self.pt_rpi_ip_3.setPlainText(_translate("MainWindow", "10.0.0.22", None))
        self.plainTextEdit_36.setPlainText(_translate("MainWindow", "4", None))
        self.pt_rpi_ip_4.setPlainText(_translate("MainWindow", "10.0.0.23", None))
        self.pb_show_image.setText(_translate("MainWindow", "Show Image", None))
        self.pb_calibrate.setText(_translate("MainWindow", "Calibrate", None))
        self.pb_show_calibration.setText(_translate("MainWindow", "Show Calibration", None))
        self.pb_overlay_calibration.setText(_translate("MainWindow", "Overlay Calibration", None))
        self.pb_test_tracking.setText(_translate("MainWindow", "Test Tracking", None))
        self.groupBox.setTitle(_translate("MainWindow", "Camera 1", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Camera 2", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Camera 3", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Camera 4", None))

from pyqtgraph import GraphicsLayoutWidget
