# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DetectWaveformsDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1132, 955)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.f_all_plots = QtGui.QFrame(self.centralwidget)
        self.f_all_plots.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_all_plots.setFrameShadow(QtGui.QFrame.Raised)
        self.f_all_plots.setObjectName(_fromUtf8("f_all_plots"))
        self.gridLayout = QtGui.QGridLayout(self.f_all_plots)
        self.gridLayout.setMargin(3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gb_Ch2 = QtGui.QGroupBox(self.f_all_plots)
        self.gb_Ch2.setMinimumSize(QtCore.QSize(450, 380))
        self.gb_Ch2.setObjectName(_fromUtf8("gb_Ch2"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.gb_Ch2)
        self.verticalLayout_15.setMargin(3)
        self.verticalLayout_15.setSpacing(3)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.f_Ch2_options = QtGui.QFrame(self.gb_Ch2)
        self.f_Ch2_options.setMaximumSize(QtCore.QSize(16777215, 35))
        self.f_Ch2_options.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_Ch2_options.setFrameShadow(QtGui.QFrame.Raised)
        self.f_Ch2_options.setObjectName(_fromUtf8("f_Ch2_options"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.f_Ch2_options)
        self.horizontalLayout_12.setMargin(3)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.sb_Ch2_threshold = QtGui.QSpinBox(self.f_Ch2_options)
        self.sb_Ch2_threshold.setMinimumSize(QtCore.QSize(140, 0))
        self.sb_Ch2_threshold.setMinimum(-9999)
        self.sb_Ch2_threshold.setMaximum(9999)
        self.sb_Ch2_threshold.setSingleStep(10)
        self.sb_Ch2_threshold.setProperty("value", -100)
        self.sb_Ch2_threshold.setObjectName(_fromUtf8("sb_Ch2_threshold"))
        self.horizontalLayout_12.addWidget(self.sb_Ch2_threshold)
        self.sb_min_Ch2 = QtGui.QSpinBox(self.f_Ch2_options)
        self.sb_min_Ch2.setMinimum(-99999)
        self.sb_min_Ch2.setMaximum(99999)
        self.sb_min_Ch2.setSingleStep(50)
        self.sb_min_Ch2.setProperty("value", -300)
        self.sb_min_Ch2.setObjectName(_fromUtf8("sb_min_Ch2"))
        self.horizontalLayout_12.addWidget(self.sb_min_Ch2)
        self.sb_max_Ch2 = QtGui.QSpinBox(self.f_Ch2_options)
        self.sb_max_Ch2.setMinimum(-99999)
        self.sb_max_Ch2.setMaximum(99999)
        self.sb_max_Ch2.setSingleStep(50)
        self.sb_max_Ch2.setProperty("value", 300)
        self.sb_max_Ch2.setObjectName(_fromUtf8("sb_max_Ch2"))
        self.horizontalLayout_12.addWidget(self.sb_max_Ch2)
        self.pb_update_ch2 = QtGui.QPushButton(self.f_Ch2_options)
        self.pb_update_ch2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pb_update_ch2.setObjectName(_fromUtf8("pb_update_ch2"))
        self.horizontalLayout_12.addWidget(self.pb_update_ch2)
        self.horizontalLayout_12.setStretch(1, 2)
        self.horizontalLayout_12.setStretch(2, 2)
        self.horizontalLayout_12.setStretch(3, 1)
        self.verticalLayout_15.addWidget(self.f_Ch2_options)
        self.frame_Ch2_plots = QtGui.QFrame(self.gb_Ch2)
        self.frame_Ch2_plots.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Ch2_plots.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Ch2_plots.setObjectName(_fromUtf8("frame_Ch2_plots"))
        self.gridLayout_19 = QtGui.QGridLayout(self.frame_Ch2_plots)
        self.gridLayout_19.setMargin(3)
        self.gridLayout_19.setSpacing(3)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.ax_Ch2_1 = PlotWidget(self.frame_Ch2_plots)
        self.ax_Ch2_1.setObjectName(_fromUtf8("ax_Ch2_1"))
        self.gridLayout_19.addWidget(self.ax_Ch2_1, 0, 0, 1, 1)
        self.ax_Ch2_2 = PlotWidget(self.frame_Ch2_plots)
        self.ax_Ch2_2.setObjectName(_fromUtf8("ax_Ch2_2"))
        self.gridLayout_19.addWidget(self.ax_Ch2_2, 0, 1, 1, 1)
        self.ax_Ch2_3 = PlotWidget(self.frame_Ch2_plots)
        self.ax_Ch2_3.setObjectName(_fromUtf8("ax_Ch2_3"))
        self.gridLayout_19.addWidget(self.ax_Ch2_3, 1, 0, 1, 1)
        self.ax_Ch2_4 = PlotWidget(self.frame_Ch2_plots)
        self.ax_Ch2_4.setObjectName(_fromUtf8("ax_Ch2_4"))
        self.gridLayout_19.addWidget(self.ax_Ch2_4, 1, 1, 1, 1)
        self.gridLayout_19.setColumnMinimumWidth(0, 1)
        self.gridLayout_19.setColumnMinimumWidth(1, 1)
        self.gridLayout_19.setRowMinimumHeight(0, 1)
        self.gridLayout_19.setRowMinimumHeight(1, 1)
        self.gridLayout_19.setColumnStretch(0, 1)
        self.gridLayout_19.setColumnStretch(1, 1)
        self.gridLayout_19.setRowStretch(0, 1)
        self.gridLayout_19.setRowStretch(1, 1)
        self.verticalLayout_15.addWidget(self.frame_Ch2_plots)
        self.gridLayout.addWidget(self.gb_Ch2, 0, 1, 1, 1)
        self.gb_Ch1 = QtGui.QGroupBox(self.f_all_plots)
        self.gb_Ch1.setMinimumSize(QtCore.QSize(450, 380))
        self.gb_Ch1.setObjectName(_fromUtf8("gb_Ch1"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.gb_Ch1)
        self.verticalLayout_8.setMargin(3)
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.f_Ch1_options = QtGui.QFrame(self.gb_Ch1)
        self.f_Ch1_options.setMaximumSize(QtCore.QSize(16777215, 35))
        self.f_Ch1_options.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_Ch1_options.setFrameShadow(QtGui.QFrame.Raised)
        self.f_Ch1_options.setObjectName(_fromUtf8("f_Ch1_options"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.f_Ch1_options)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sb_Ch1_threshold = QtGui.QSpinBox(self.f_Ch1_options)
        self.sb_Ch1_threshold.setMinimumSize(QtCore.QSize(140, 0))
        self.sb_Ch1_threshold.setMinimum(-9999)
        self.sb_Ch1_threshold.setMaximum(9999)
        self.sb_Ch1_threshold.setSingleStep(10)
        self.sb_Ch1_threshold.setProperty("value", -100)
        self.sb_Ch1_threshold.setObjectName(_fromUtf8("sb_Ch1_threshold"))
        self.horizontalLayout.addWidget(self.sb_Ch1_threshold)
        self.sb_min_Ch1 = QtGui.QSpinBox(self.f_Ch1_options)
        self.sb_min_Ch1.setMinimum(-99999)
        self.sb_min_Ch1.setMaximum(99999)
        self.sb_min_Ch1.setSingleStep(50)
        self.sb_min_Ch1.setProperty("value", -300)
        self.sb_min_Ch1.setObjectName(_fromUtf8("sb_min_Ch1"))
        self.horizontalLayout.addWidget(self.sb_min_Ch1)
        self.sb_max_Ch1 = QtGui.QSpinBox(self.f_Ch1_options)
        self.sb_max_Ch1.setMinimum(-99999)
        self.sb_max_Ch1.setMaximum(99999)
        self.sb_max_Ch1.setSingleStep(50)
        self.sb_max_Ch1.setProperty("value", 300)
        self.sb_max_Ch1.setObjectName(_fromUtf8("sb_max_Ch1"))
        self.horizontalLayout.addWidget(self.sb_max_Ch1)
        self.pb_update_ch1 = QtGui.QPushButton(self.f_Ch1_options)
        self.pb_update_ch1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pb_update_ch1.setObjectName(_fromUtf8("pb_update_ch1"))
        self.horizontalLayout.addWidget(self.pb_update_ch1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_8.addWidget(self.f_Ch1_options)
        self.frame_Ch1_plots = QtGui.QFrame(self.gb_Ch1)
        self.frame_Ch1_plots.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Ch1_plots.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Ch1_plots.setObjectName(_fromUtf8("frame_Ch1_plots"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_Ch1_plots)
        self.gridLayout_8.setMargin(3)
        self.gridLayout_8.setSpacing(3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.ax_Ch1_1 = PlotWidget(self.frame_Ch1_plots)
        self.ax_Ch1_1.setObjectName(_fromUtf8("ax_Ch1_1"))
        self.gridLayout_8.addWidget(self.ax_Ch1_1, 0, 0, 1, 1)
        self.ax_Ch1_3 = PlotWidget(self.frame_Ch1_plots)
        self.ax_Ch1_3.setObjectName(_fromUtf8("ax_Ch1_3"))
        self.gridLayout_8.addWidget(self.ax_Ch1_3, 1, 0, 1, 1)
        self.ax_Ch1_2 = PlotWidget(self.frame_Ch1_plots)
        self.ax_Ch1_2.setObjectName(_fromUtf8("ax_Ch1_2"))
        self.gridLayout_8.addWidget(self.ax_Ch1_2, 0, 1, 1, 1)
        self.ax_Ch1_4 = PlotWidget(self.frame_Ch1_plots)
        self.ax_Ch1_4.setObjectName(_fromUtf8("ax_Ch1_4"))
        self.gridLayout_8.addWidget(self.ax_Ch1_4, 1, 1, 1, 1)
        self.gridLayout_8.setColumnMinimumWidth(0, 1)
        self.gridLayout_8.setColumnMinimumWidth(1, 1)
        self.gridLayout_8.setRowMinimumHeight(0, 1)
        self.gridLayout_8.setRowMinimumHeight(1, 1)
        self.gridLayout_8.setColumnStretch(0, 1)
        self.gridLayout_8.setColumnStretch(1, 1)
        self.gridLayout_8.setRowStretch(0, 1)
        self.gridLayout_8.setRowStretch(1, 1)
        self.verticalLayout_8.addWidget(self.frame_Ch1_plots)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.gridLayout.addWidget(self.gb_Ch1, 0, 0, 1, 1)
        self.gb_Ch3 = QtGui.QGroupBox(self.f_all_plots)
        self.gb_Ch3.setMinimumSize(QtCore.QSize(450, 380))
        self.gb_Ch3.setObjectName(_fromUtf8("gb_Ch3"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.gb_Ch3)
        self.verticalLayout_16.setMargin(3)
        self.verticalLayout_16.setSpacing(3)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.f_Ch3_options = QtGui.QFrame(self.gb_Ch3)
        self.f_Ch3_options.setMaximumSize(QtCore.QSize(16777215, 35))
        self.f_Ch3_options.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_Ch3_options.setFrameShadow(QtGui.QFrame.Raised)
        self.f_Ch3_options.setObjectName(_fromUtf8("f_Ch3_options"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.f_Ch3_options)
        self.horizontalLayout_13.setMargin(3)
        self.horizontalLayout_13.setSpacing(3)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.sb_Ch3_threshold = QtGui.QSpinBox(self.f_Ch3_options)
        self.sb_Ch3_threshold.setMinimumSize(QtCore.QSize(140, 0))
        self.sb_Ch3_threshold.setSuffix(_fromUtf8(""))
        self.sb_Ch3_threshold.setMinimum(-9999)
        self.sb_Ch3_threshold.setMaximum(9999)
        self.sb_Ch3_threshold.setSingleStep(10)
        self.sb_Ch3_threshold.setProperty("value", -100)
        self.sb_Ch3_threshold.setObjectName(_fromUtf8("sb_Ch3_threshold"))
        self.horizontalLayout_13.addWidget(self.sb_Ch3_threshold)
        self.sb_min_Ch3 = QtGui.QSpinBox(self.f_Ch3_options)
        self.sb_min_Ch3.setMinimum(-99999)
        self.sb_min_Ch3.setMaximum(99999)
        self.sb_min_Ch3.setSingleStep(50)
        self.sb_min_Ch3.setProperty("value", -300)
        self.sb_min_Ch3.setObjectName(_fromUtf8("sb_min_Ch3"))
        self.horizontalLayout_13.addWidget(self.sb_min_Ch3)
        self.sb_max_Ch3 = QtGui.QSpinBox(self.f_Ch3_options)
        self.sb_max_Ch3.setMinimum(-99999)
        self.sb_max_Ch3.setMaximum(99999)
        self.sb_max_Ch3.setSingleStep(50)
        self.sb_max_Ch3.setProperty("value", 300)
        self.sb_max_Ch3.setObjectName(_fromUtf8("sb_max_Ch3"))
        self.horizontalLayout_13.addWidget(self.sb_max_Ch3)
        self.pb_update_ch3 = QtGui.QPushButton(self.f_Ch3_options)
        self.pb_update_ch3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pb_update_ch3.setObjectName(_fromUtf8("pb_update_ch3"))
        self.horizontalLayout_13.addWidget(self.pb_update_ch3)
        self.horizontalLayout_13.setStretch(1, 2)
        self.horizontalLayout_13.setStretch(2, 2)
        self.horizontalLayout_13.setStretch(3, 1)
        self.verticalLayout_16.addWidget(self.f_Ch3_options)
        self.frame_Ch3_plots = QtGui.QFrame(self.gb_Ch3)
        self.frame_Ch3_plots.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Ch3_plots.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Ch3_plots.setObjectName(_fromUtf8("frame_Ch3_plots"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frame_Ch3_plots)
        self.gridLayout_20.setMargin(3)
        self.gridLayout_20.setSpacing(3)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.ax_Ch3_1 = PlotWidget(self.frame_Ch3_plots)
        self.ax_Ch3_1.setObjectName(_fromUtf8("ax_Ch3_1"))
        self.gridLayout_20.addWidget(self.ax_Ch3_1, 0, 0, 1, 1)
        self.ax_Ch3_2 = PlotWidget(self.frame_Ch3_plots)
        self.ax_Ch3_2.setObjectName(_fromUtf8("ax_Ch3_2"))
        self.gridLayout_20.addWidget(self.ax_Ch3_2, 0, 1, 1, 1)
        self.ax_Ch3_3 = PlotWidget(self.frame_Ch3_plots)
        self.ax_Ch3_3.setObjectName(_fromUtf8("ax_Ch3_3"))
        self.gridLayout_20.addWidget(self.ax_Ch3_3, 1, 0, 1, 1)
        self.ax_Ch3_4 = PlotWidget(self.frame_Ch3_plots)
        self.ax_Ch3_4.setObjectName(_fromUtf8("ax_Ch3_4"))
        self.gridLayout_20.addWidget(self.ax_Ch3_4, 1, 1, 1, 1)
        self.gridLayout_20.setColumnMinimumWidth(0, 1)
        self.gridLayout_20.setColumnMinimumWidth(1, 1)
        self.gridLayout_20.setRowMinimumHeight(0, 1)
        self.gridLayout_20.setRowMinimumHeight(1, 1)
        self.gridLayout_20.setColumnStretch(0, 1)
        self.gridLayout_20.setColumnStretch(1, 1)
        self.gridLayout_20.setRowStretch(0, 1)
        self.gridLayout_20.setRowStretch(1, 1)
        self.verticalLayout_16.addWidget(self.frame_Ch3_plots)
        self.gridLayout.addWidget(self.gb_Ch3, 1, 0, 1, 1)
        self.gb_Ch4 = QtGui.QGroupBox(self.f_all_plots)
        self.gb_Ch4.setMinimumSize(QtCore.QSize(450, 380))
        self.gb_Ch4.setObjectName(_fromUtf8("gb_Ch4"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.gb_Ch4)
        self.verticalLayout_17.setMargin(3)
        self.verticalLayout_17.setSpacing(3)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.f_Ch4_options = QtGui.QFrame(self.gb_Ch4)
        self.f_Ch4_options.setMaximumSize(QtCore.QSize(16777215, 35))
        self.f_Ch4_options.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_Ch4_options.setFrameShadow(QtGui.QFrame.Raised)
        self.f_Ch4_options.setObjectName(_fromUtf8("f_Ch4_options"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.f_Ch4_options)
        self.horizontalLayout_14.setMargin(3)
        self.horizontalLayout_14.setSpacing(3)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.sb_Ch4_threshold = QtGui.QSpinBox(self.f_Ch4_options)
        self.sb_Ch4_threshold.setMinimumSize(QtCore.QSize(140, 0))
        self.sb_Ch4_threshold.setMinimum(-9999)
        self.sb_Ch4_threshold.setMaximum(9999)
        self.sb_Ch4_threshold.setSingleStep(10)
        self.sb_Ch4_threshold.setProperty("value", -100)
        self.sb_Ch4_threshold.setObjectName(_fromUtf8("sb_Ch4_threshold"))
        self.horizontalLayout_14.addWidget(self.sb_Ch4_threshold)
        self.sb_min_Ch4 = QtGui.QSpinBox(self.f_Ch4_options)
        self.sb_min_Ch4.setMinimum(-99999)
        self.sb_min_Ch4.setMaximum(99999)
        self.sb_min_Ch4.setSingleStep(50)
        self.sb_min_Ch4.setProperty("value", -300)
        self.sb_min_Ch4.setObjectName(_fromUtf8("sb_min_Ch4"))
        self.horizontalLayout_14.addWidget(self.sb_min_Ch4)
        self.sb_max_Ch4 = QtGui.QSpinBox(self.f_Ch4_options)
        self.sb_max_Ch4.setMinimum(-99999)
        self.sb_max_Ch4.setMaximum(99999)
        self.sb_max_Ch4.setSingleStep(50)
        self.sb_max_Ch4.setProperty("value", 300)
        self.sb_max_Ch4.setObjectName(_fromUtf8("sb_max_Ch4"))
        self.horizontalLayout_14.addWidget(self.sb_max_Ch4)
        self.pb_update_ch4 = QtGui.QPushButton(self.f_Ch4_options)
        self.pb_update_ch4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pb_update_ch4.setObjectName(_fromUtf8("pb_update_ch4"))
        self.horizontalLayout_14.addWidget(self.pb_update_ch4)
        self.horizontalLayout_14.setStretch(1, 2)
        self.horizontalLayout_14.setStretch(2, 2)
        self.horizontalLayout_14.setStretch(3, 1)
        self.verticalLayout_17.addWidget(self.f_Ch4_options)
        self.frame_Ch4_plots = QtGui.QFrame(self.gb_Ch4)
        self.frame_Ch4_plots.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Ch4_plots.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Ch4_plots.setObjectName(_fromUtf8("frame_Ch4_plots"))
        self.gridLayout_21 = QtGui.QGridLayout(self.frame_Ch4_plots)
        self.gridLayout_21.setMargin(3)
        self.gridLayout_21.setSpacing(3)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.ax_Ch4_1 = PlotWidget(self.frame_Ch4_plots)
        self.ax_Ch4_1.setObjectName(_fromUtf8("ax_Ch4_1"))
        self.gridLayout_21.addWidget(self.ax_Ch4_1, 0, 0, 1, 1)
        self.ax_Ch4_2 = PlotWidget(self.frame_Ch4_plots)
        self.ax_Ch4_2.setObjectName(_fromUtf8("ax_Ch4_2"))
        self.gridLayout_21.addWidget(self.ax_Ch4_2, 0, 1, 1, 1)
        self.ax_Ch4_3 = PlotWidget(self.frame_Ch4_plots)
        self.ax_Ch4_3.setObjectName(_fromUtf8("ax_Ch4_3"))
        self.gridLayout_21.addWidget(self.ax_Ch4_3, 1, 0, 1, 1)
        self.ax_Ch4_4 = PlotWidget(self.frame_Ch4_plots)
        self.ax_Ch4_4.setObjectName(_fromUtf8("ax_Ch4_4"))
        self.gridLayout_21.addWidget(self.ax_Ch4_4, 1, 1, 1, 1)
        self.gridLayout_21.setColumnMinimumWidth(0, 1)
        self.gridLayout_21.setColumnMinimumWidth(1, 1)
        self.gridLayout_21.setRowMinimumHeight(0, 1)
        self.gridLayout_21.setRowMinimumHeight(1, 1)
        self.gridLayout_21.setColumnStretch(0, 1)
        self.gridLayout_21.setColumnStretch(1, 1)
        self.gridLayout_21.setRowStretch(0, 1)
        self.gridLayout_21.setRowStretch(1, 1)
        self.verticalLayout_17.addWidget(self.frame_Ch4_plots)
        self.gridLayout.addWidget(self.gb_Ch4, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gb_Ch4.raise_()
        self.gb_Ch3.raise_()
        self.gb_Ch2.raise_()
        self.gb_Ch1.raise_()
        self.horizontalLayout_2.addWidget(self.f_all_plots)
        self.f_buttons_2 = QtGui.QFrame(self.centralwidget)
        self.f_buttons_2.setMinimumSize(QtCore.QSize(180, 0))
        self.f_buttons_2.setMaximumSize(QtCore.QSize(165, 16777215))
        self.f_buttons_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_buttons_2.setFrameShadow(QtGui.QFrame.Raised)
        self.f_buttons_2.setObjectName(_fromUtf8("f_buttons_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.f_buttons_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cb_reference = QtGui.QCheckBox(self.f_buttons_2)
        self.cb_reference.setChecked(True)
        self.cb_reference.setObjectName(_fromUtf8("cb_reference"))
        self.verticalLayout.addWidget(self.cb_reference)
        self.cb_filter = QtGui.QCheckBox(self.f_buttons_2)
        self.cb_filter.setChecked(True)
        self.cb_filter.setObjectName(_fromUtf8("cb_filter"))
        self.verticalLayout.addWidget(self.cb_filter)
        self.pb_load_all_channels = QtGui.QPushButton(self.f_buttons_2)
        self.pb_load_all_channels.setObjectName(_fromUtf8("pb_load_all_channels"))
        self.verticalLayout.addWidget(self.pb_load_all_channels)
        self.pb_plot_trace = QtGui.QPushButton(self.f_buttons_2)
        self.pb_plot_trace.setObjectName(_fromUtf8("pb_plot_trace"))
        self.verticalLayout.addWidget(self.pb_plot_trace)
        self.frame = QtGui.QFrame(self.f_buttons_2)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(40, 29))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.gridLayout_2.addWidget(self.plainTextEdit_2, 1, 0, 1, 1)
        self.pt_lfp_ch = QtGui.QPlainTextEdit(self.frame)
        self.pt_lfp_ch.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pt_lfp_ch.setObjectName(_fromUtf8("pt_lfp_ch"))
        self.gridLayout_2.addWidget(self.pt_lfp_ch, 1, 1, 1, 1)
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit_4.setMaximumSize(QtCore.QSize(40, 29))
        self.plainTextEdit_4.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.gridLayout_2.addWidget(self.plainTextEdit_4, 0, 0, 1, 1)
        self.pt_lfp_tet = QtGui.QPlainTextEdit(self.frame)
        self.pt_lfp_tet.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pt_lfp_tet.setObjectName(_fromUtf8("pt_lfp_tet"))
        self.gridLayout_2.addWidget(self.pt_lfp_tet, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.f_buttons_2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.plainTextEdit_5 = QtGui.QPlainTextEdit(self.frame_2)
        self.plainTextEdit_5.setMinimumSize(QtCore.QSize(95, 0))
        self.plainTextEdit_5.setMaximumSize(QtCore.QSize(95, 29))
        self.plainTextEdit_5.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setObjectName(_fromUtf8("plainTextEdit_5"))
        self.horizontalLayout_6.addWidget(self.plainTextEdit_5)
        self.pt_default_threshold = QtGui.QPlainTextEdit(self.frame_2)
        self.pt_default_threshold.setMinimumSize(QtCore.QSize(40, 0))
        self.pt_default_threshold.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pt_default_threshold.setObjectName(_fromUtf8("pt_default_threshold"))
        self.horizontalLayout_6.addWidget(self.pt_default_threshold)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.f_buttons_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.frame_3)
        self.plainTextEdit_3.setMaximumSize(QtCore.QSize(16777215, 29))
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.horizontalLayout_4.addWidget(self.plainTextEdit_3)
        self.pt_noise_threshold = QtGui.QPlainTextEdit(self.frame_3)
        self.pt_noise_threshold.setMaximumSize(QtCore.QSize(35, 29))
        self.pt_noise_threshold.setObjectName(_fromUtf8("pt_noise_threshold"))
        self.horizontalLayout_4.addWidget(self.pt_noise_threshold)
        self.plainTextEdit_7 = QtGui.QPlainTextEdit(self.frame_3)
        self.plainTextEdit_7.setMaximumSize(QtCore.QSize(20, 29))
        self.plainTextEdit_7.setReadOnly(True)
        self.plainTextEdit_7.setObjectName(_fromUtf8("plainTextEdit_7"))
        self.horizontalLayout_4.addWidget(self.plainTextEdit_7)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pb_prev = QtGui.QPushButton(self.f_buttons_2)
        self.pb_prev.setObjectName(_fromUtf8("pb_prev"))
        self.horizontalLayout_3.addWidget(self.pb_prev)
        self.pb_next = QtGui.QPushButton(self.f_buttons_2)
        self.pb_next.setObjectName(_fromUtf8("pb_next"))
        self.horizontalLayout_3.addWidget(self.pb_next)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.lw_tetrodes = QtGui.QListWidget(self.f_buttons_2)
        self.lw_tetrodes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lw_tetrodes.setFont(font)
        self.lw_tetrodes.setObjectName(_fromUtf8("lw_tetrodes"))
        self.verticalLayout.addWidget(self.lw_tetrodes)
        self.cb_toggle_axes = QtGui.QCheckBox(self.f_buttons_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_toggle_axes.setFont(font)
        self.cb_toggle_axes.setObjectName(_fromUtf8("cb_toggle_axes"))
        self.verticalLayout.addWidget(self.cb_toggle_axes)
        self.pb_save_waveforms = QtGui.QPushButton(self.f_buttons_2)
        self.pb_save_waveforms.setObjectName(_fromUtf8("pb_save_waveforms"))
        self.verticalLayout.addWidget(self.pb_save_waveforms)
        self.pb_klustakwik = QtGui.QPushButton(self.f_buttons_2)
        self.pb_klustakwik.setObjectName(_fromUtf8("pb_klustakwik"))
        self.verticalLayout.addWidget(self.pb_klustakwik)
        self.pb_load_individual_channels = QtGui.QPushButton(self.f_buttons_2)
        self.pb_load_individual_channels.setObjectName(_fromUtf8("pb_load_individual_channels"))
        self.verticalLayout.addWidget(self.pb_load_individual_channels)
        self.horizontalLayout_2.addWidget(self.f_buttons_2)
        self.horizontalLayout_2.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.gb_Ch2.setTitle(_translate("MainWindow", "Channel 2", None))
        self.sb_Ch2_threshold.setPrefix(_translate("MainWindow", "threshold: ", None))
        self.sb_min_Ch2.setPrefix(_translate("MainWindow", "min ", None))
        self.sb_max_Ch2.setPrefix(_translate("MainWindow", "max ", None))
        self.pb_update_ch2.setText(_translate("MainWindow", "Update", None))
        self.gb_Ch1.setTitle(_translate("MainWindow", "Channel 1", None))
        self.sb_Ch1_threshold.setPrefix(_translate("MainWindow", "threshold: ", None))
        self.sb_min_Ch1.setPrefix(_translate("MainWindow", "min ", None))
        self.sb_max_Ch1.setPrefix(_translate("MainWindow", "max ", None))
        self.pb_update_ch1.setText(_translate("MainWindow", "Update", None))
        self.gb_Ch3.setTitle(_translate("MainWindow", "Channel 3", None))
        self.sb_Ch3_threshold.setPrefix(_translate("MainWindow", "threshold: ", None))
        self.sb_min_Ch3.setPrefix(_translate("MainWindow", "min ", None))
        self.sb_max_Ch3.setPrefix(_translate("MainWindow", "max ", None))
        self.pb_update_ch3.setText(_translate("MainWindow", "Update", None))
        self.gb_Ch4.setTitle(_translate("MainWindow", "Channel 4", None))
        self.sb_Ch4_threshold.setPrefix(_translate("MainWindow", "threshold: ", None))
        self.sb_min_Ch4.setPrefix(_translate("MainWindow", "min ", None))
        self.sb_max_Ch4.setPrefix(_translate("MainWindow", "max ", None))
        self.pb_update_ch4.setText(_translate("MainWindow", "Update", None))
        self.cb_reference.setText(_translate("MainWindow", "Referencing", None))
        self.cb_filter.setText(_translate("MainWindow", "Filtering", None))
        self.pb_load_all_channels.setText(_translate("MainWindow", "Load All Tetrodes", None))
        self.pb_plot_trace.setText(_translate("MainWindow", "Plot LFP for:", None))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "Ch:", None))
        self.pt_lfp_ch.setPlainText(_translate("MainWindow", "1", None))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "Tet:", None))
        self.pt_lfp_tet.setPlainText(_translate("MainWindow", "1", None))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "d.Threshold:", None))
        self.pt_default_threshold.setPlainText(_translate("MainWindow", "-100", None))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "Max Spike:", None))
        self.pt_noise_threshold.setPlainText(_translate("MainWindow", "0.5", None))
        self.plainTextEdit_7.setPlainText(_translate("MainWindow", "V", None))
        self.pb_prev.setText(_translate("MainWindow", "Previous", None))
        self.pb_next.setText(_translate("MainWindow", "Next", None))
        self.cb_toggle_axes.setText(_translate("MainWindow", "Display Axes (uV,ms)", None))
        self.pb_save_waveforms.setText(_translate("MainWindow", "Save Waveforms", None))
        self.pb_klustakwik.setText(_translate("MainWindow", "Apply KlustaKwik", None))
        self.pb_load_individual_channels.setText(_translate("MainWindow", "Load each channel", None))

from pyqtgraph import PlotWidget
# These lines need to be added to the end of the DetectWaveformsDesign.py
# that is created from QtDesigner's .ui file. This allows clicking on the
# plots to be detected.

# By Sander Tanni, January 2017, UCL

from PyQt4.QtCore import QObject, pyqtSignal
class MouseClick(QObject):
    clicked = pyqtSignal()
    def __init__(self):
        # Initialize the MouseClick as a QObject
        QObject.__init__(self)
    def SendClick(self):
        self.clicked.emit()
class PlotWidget(PlotWidget):
    def __init__(self, parent=None):
        super(PlotWidget, self).__init__(parent=parent)
        self.mousePress = pyqtSignal()
        self.mouseClickObject = MouseClick()
    def mousePressEvent(self, ev):
        super(PlotWidget, self).mousePressEvent(ev=ev)
        self.mouseClickObject.SendClick()    
