# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecordingManagerDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(835, 610)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.scroll_info = QtGui.QScrollArea(self.centralwidget)
        self.scroll_info.setMinimumSize(QtCore.QSize(370, 0))
        self.scroll_info.setWidgetResizable(True)
        self.scroll_info.setObjectName(_fromUtf8("scroll_info"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 537, 543))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.f_experimenter = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.f_experimenter.setMaximumSize(QtCore.QSize(16777215, 49))
        self.f_experimenter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_experimenter.setFrameShadow(QtGui.QFrame.Raised)
        self.f_experimenter.setObjectName(_fromUtf8("f_experimenter"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.f_experimenter)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_2 = QtGui.QLabel(self.f_experimenter)
        self.label_2.setMinimumSize(QtCore.QSize(180, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_17.addWidget(self.label_2)
        self.pb_experimenter = QtGui.QPushButton(self.f_experimenter)
        self.pb_experimenter.setEnabled(True)
        self.pb_experimenter.setMinimumSize(QtCore.QSize(85, 29))
        self.pb_experimenter.setMaximumSize(QtCore.QSize(85, 29))
        self.pb_experimenter.setObjectName(_fromUtf8("pb_experimenter"))
        self.horizontalLayout_17.addWidget(self.pb_experimenter)
        self.pt_experimenter = QtGui.QPlainTextEdit(self.f_experimenter)
        self.pt_experimenter.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pt_experimenter.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_experimenter.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_experimenter.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.pt_experimenter.setObjectName(_fromUtf8("pt_experimenter"))
        self.horizontalLayout_17.addWidget(self.pt_experimenter)
        self.verticalLayout.addWidget(self.f_experimenter)
        self.f_root_folder = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.f_root_folder.setMaximumSize(QtCore.QSize(16777215, 49))
        self.f_root_folder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_root_folder.setFrameShadow(QtGui.QFrame.Raised)
        self.f_root_folder.setObjectName(_fromUtf8("f_root_folder"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.f_root_folder)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_3 = QtGui.QLabel(self.f_root_folder)
        self.label_3.setMinimumSize(QtCore.QSize(180, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_21.addWidget(self.label_3)
        self.pb_root_folder = QtGui.QPushButton(self.f_root_folder)
        self.pb_root_folder.setMinimumSize(QtCore.QSize(85, 29))
        self.pb_root_folder.setMaximumSize(QtCore.QSize(85, 29))
        self.pb_root_folder.setObjectName(_fromUtf8("pb_root_folder"))
        self.horizontalLayout_21.addWidget(self.pb_root_folder)
        self.pt_root_folder = QtGui.QPlainTextEdit(self.f_root_folder)
        self.pt_root_folder.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pt_root_folder.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_root_folder.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_root_folder.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.pt_root_folder.setObjectName(_fromUtf8("pt_root_folder"))
        self.horizontalLayout_21.addWidget(self.pt_root_folder)
        self.verticalLayout.addWidget(self.f_root_folder)
        self.f_animal = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.f_animal.setMaximumSize(QtCore.QSize(16777215, 49))
        self.f_animal.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.f_animal.setObjectName(_fromUtf8("f_animal"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.f_animal)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtGui.QLabel(self.f_animal)
        self.label_4.setMinimumSize(QtCore.QSize(180, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.pb_animal = QtGui.QPushButton(self.f_animal)
        self.pb_animal.setEnabled(True)
        self.pb_animal.setMinimumSize(QtCore.QSize(85, 29))
        self.pb_animal.setMaximumSize(QtCore.QSize(85, 29))
        self.pb_animal.setObjectName(_fromUtf8("pb_animal"))
        self.horizontalLayout_9.addWidget(self.pb_animal)
        self.pt_animal = QtGui.QPlainTextEdit(self.f_animal)
        self.pt_animal.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pt_animal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_animal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_animal.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.pt_animal.setObjectName(_fromUtf8("pt_animal"))
        self.horizontalLayout_9.addWidget(self.pt_animal)
        self.verticalLayout.addWidget(self.f_animal)
        self.f_experiment = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.f_experiment.setMaximumSize(QtCore.QSize(16777215, 49))
        self.f_experiment.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_experiment.setFrameShadow(QtGui.QFrame.Raised)
        self.f_experiment.setObjectName(_fromUtf8("f_experiment"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.f_experiment)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_5 = QtGui.QLabel(self.f_experiment)
        self.label_5.setMinimumSize(QtCore.QSize(180, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_19.addWidget(self.label_5)
        self.pb_experiment_id = QtGui.QPushButton(self.f_experiment)
        self.pb_experiment_id.setEnabled(True)
        self.pb_experiment_id.setMinimumSize(QtCore.QSize(85, 29))
        self.pb_experiment_id.setMaximumSize(QtCore.QSize(85, 29))
        self.pb_experiment_id.setObjectName(_fromUtf8("pb_experiment_id"))
        self.horizontalLayout_19.addWidget(self.pb_experiment_id)
        self.pt_experiment_id = QtGui.QPlainTextEdit(self.f_experiment)
        self.pt_experiment_id.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pt_experiment_id.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_experiment_id.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_experiment_id.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.pt_experiment_id.setObjectName(_fromUtf8("pt_experiment_id"))
        self.horizontalLayout_19.addWidget(self.pt_experiment_id)
        self.verticalLayout.addWidget(self.f_experiment)
        self.f_badChan_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.f_badChan_3.setMaximumSize(QtCore.QSize(16777215, 49))
        self.f_badChan_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_badChan_3.setFrameShadow(QtGui.QFrame.Raised)
        self.f_badChan_3.setObjectName(_fromUtf8("f_badChan_3"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.f_badChan_3)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_10 = QtGui.QLabel(self.f_badChan_3)
        self.label_10.setMinimumSize(QtCore.QSize(180, 0))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_24.addWidget(self.label_10)
        self.frame_7 = QtGui.QFrame(self.f_badChan_3)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 31))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_11 = QtGui.QLabel(self.frame_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_8.addWidget(self.label_11)
        self.pt_arena_size_x = QtGui.QPlainTextEdit(self.frame_7)
        self.pt_arena_size_x.setMinimumSize(QtCore.QSize(40, 29))
        self.pt_arena_size_x.setObjectName(_fromUtf8("pt_arena_size_x"))
        self.horizontalLayout_8.addWidget(self.pt_arena_size_x)
        self.label_12 = QtGui.QLabel(self.frame_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        self.pt_arena_size_y = QtGui.QPlainTextEdit(self.frame_7)
        self.pt_arena_size_y.setMinimumSize(QtCore.QSize(40, 29))
        self.pt_arena_size_y.setObjectName(_fromUtf8("pt_arena_size_y"))
        self.horizontalLayout_8.addWidget(self.pt_arena_size_y)
        self.horizontalLayout_24.addWidget(self.frame_7)
        self.horizontalLayout_24.setStretch(1, 3)
        self.verticalLayout.addWidget(self.f_badChan_3)
        self.f_badChan_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.f_badChan_2.setMaximumSize(QtCore.QSize(16777215, 49))
        self.f_badChan_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_badChan_2.setFrameShadow(QtGui.QFrame.Raised)
        self.f_badChan_2.setObjectName(_fromUtf8("f_badChan_2"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.f_badChan_2)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_6 = QtGui.QLabel(self.f_badChan_2)
        self.label_6.setMinimumSize(QtCore.QSize(180, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_23.addWidget(self.label_6)
        self.frame_4 = QtGui.QFrame(self.f_badChan_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 31))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pt_chan_map_1 = QtGui.QPlainTextEdit(self.frame_4)
        self.pt_chan_map_1.setMinimumSize(QtCore.QSize(50, 29))
        self.pt_chan_map_1.setObjectName(_fromUtf8("pt_chan_map_1"))
        self.horizontalLayout_5.addWidget(self.pt_chan_map_1)
        self.pt_chan_map_1_chans = QtGui.QPlainTextEdit(self.frame_4)
        self.pt_chan_map_1_chans.setMinimumSize(QtCore.QSize(70, 29))
        self.pt_chan_map_1_chans.setObjectName(_fromUtf8("pt_chan_map_1_chans"))
        self.horizontalLayout_5.addWidget(self.pt_chan_map_1_chans)
        self.pt_chan_map_2 = QtGui.QPlainTextEdit(self.frame_4)
        self.pt_chan_map_2.setMinimumSize(QtCore.QSize(50, 29))
        self.pt_chan_map_2.setObjectName(_fromUtf8("pt_chan_map_2"))
        self.horizontalLayout_5.addWidget(self.pt_chan_map_2)
        self.pt_chan_map_2_chans = QtGui.QPlainTextEdit(self.frame_4)
        self.pt_chan_map_2_chans.setMinimumSize(QtCore.QSize(70, 29))
        self.pt_chan_map_2_chans.setObjectName(_fromUtf8("pt_chan_map_2_chans"))
        self.horizontalLayout_5.addWidget(self.pt_chan_map_2_chans)
        self.horizontalLayout_23.addWidget(self.frame_4)
        self.horizontalLayout_23.setStretch(1, 3)
        self.verticalLayout.addWidget(self.f_badChan_2)
        self.f_badChan = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.f_badChan.setMaximumSize(QtCore.QSize(16777215, 49))
        self.f_badChan.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_badChan.setFrameShadow(QtGui.QFrame.Raised)
        self.f_badChan.setObjectName(_fromUtf8("f_badChan"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.f_badChan)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_7 = QtGui.QLabel(self.f_badChan)
        self.label_7.setMinimumSize(QtCore.QSize(180, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_22.addWidget(self.label_7)
        self.pt_badChan = QtGui.QPlainTextEdit(self.f_badChan)
        self.pt_badChan.setMaximumSize(QtCore.QSize(16777215, 29))
        self.pt_badChan.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_badChan.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_badChan.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.pt_badChan.setPlainText(_fromUtf8(""))
        self.pt_badChan.setObjectName(_fromUtf8("pt_badChan"))
        self.horizontalLayout_22.addWidget(self.pt_badChan)
        self.horizontalLayout_22.setStretch(1, 1)
        self.verticalLayout.addWidget(self.f_badChan)
        self.scroll_info.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scroll_info)
        self.f_buttons = QtGui.QFrame(self.centralwidget)
        self.f_buttons.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_buttons.setFrameShadow(QtGui.QFrame.Raised)
        self.f_buttons.setObjectName(_fromUtf8("f_buttons"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.f_buttons)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pb_load_last = QtGui.QPushButton(self.f_buttons)
        self.pb_load_last.setObjectName(_fromUtf8("pb_load_last"))
        self.verticalLayout_2.addWidget(self.pb_load_last)
        self.pb_load = QtGui.QPushButton(self.f_buttons)
        self.pb_load.setObjectName(_fromUtf8("pb_load"))
        self.verticalLayout_2.addWidget(self.pb_load)
        self.pb_save = QtGui.QPushButton(self.f_buttons)
        self.pb_save.setObjectName(_fromUtf8("pb_save"))
        self.verticalLayout_2.addWidget(self.pb_save)
        self.pb_cam_set = QtGui.QPushButton(self.f_buttons)
        self.pb_cam_set.setObjectName(_fromUtf8("pb_cam_set"))
        self.verticalLayout_2.addWidget(self.pb_cam_set)
        self.pb_task_set = QtGui.QPushButton(self.f_buttons)
        self.pb_task_set.setObjectName(_fromUtf8("pb_task_set"))
        self.verticalLayout_2.addWidget(self.pb_task_set)
        self.pb_test_devices = QtGui.QPushButton(self.f_buttons)
        self.pb_test_devices.setObjectName(_fromUtf8("pb_test_devices"))
        self.verticalLayout_2.addWidget(self.pb_test_devices)
        self.f_rec_folder = QtGui.QFrame(self.f_buttons)
        self.f_rec_folder.setMaximumSize(QtCore.QSize(16777215, 140))
        self.f_rec_folder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_rec_folder.setFrameShadow(QtGui.QFrame.Raised)
        self.f_rec_folder.setObjectName(_fromUtf8("f_rec_folder"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.f_rec_folder)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.f_rec_folder)
        self.label.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.pt_rec_file = QtGui.QPlainTextEdit(self.f_rec_folder)
        self.pt_rec_file.setMinimumSize(QtCore.QSize(250, 0))
        self.pt_rec_file.setMaximumSize(QtCore.QSize(16777215, 90))
        self.pt_rec_file.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_rec_file.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_rec_file.setLineWrapMode(QtGui.QPlainTextEdit.WidgetWidth)
        self.pt_rec_file.setReadOnly(True)
        self.pt_rec_file.setObjectName(_fromUtf8("pt_rec_file"))
        self.verticalLayout_4.addWidget(self.pt_rec_file)
        self.verticalLayout_2.addWidget(self.f_rec_folder)
        self.frame_2 = QtGui.QFrame(self.f_buttons)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setMargin(3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.rb_tracking_yes = QtGui.QRadioButton(self.frame_3)
        self.rb_tracking_yes.setChecked(True)
        self.rb_tracking_yes.setObjectName(_fromUtf8("rb_tracking_yes"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rb_tracking_yes)
        self.horizontalLayout_4.addWidget(self.rb_tracking_yes)
        self.rb_tracking_no = QtGui.QRadioButton(self.frame_3)
        self.rb_tracking_no.setObjectName(_fromUtf8("rb_tracking_no"))
        self.buttonGroup.addButton(self.rb_tracking_no)
        self.horizontalLayout_4.addWidget(self.rb_tracking_no)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_5 = QtGui.QFrame(self.f_buttons)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setMargin(3)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.frame_6 = QtGui.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.rb_task_yes = QtGui.QRadioButton(self.frame_6)
        self.rb_task_yes.setChecked(True)
        self.rb_task_yes.setObjectName(_fromUtf8("rb_task_yes"))
        self.horizontalLayout_7.addWidget(self.rb_task_yes)
        self.rb_task_no = QtGui.QRadioButton(self.frame_6)
        self.rb_task_no.setObjectName(_fromUtf8("rb_task_no"))
        self.horizontalLayout_7.addWidget(self.rb_task_no)
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.pb_start_rec = QtGui.QPushButton(self.f_buttons)
        self.pb_start_rec.setEnabled(True)
        self.pb_start_rec.setObjectName(_fromUtf8("pb_start_rec"))
        self.verticalLayout_2.addWidget(self.pb_start_rec)
        self.pb_stop_rec = QtGui.QPushButton(self.f_buttons)
        self.pb_stop_rec.setEnabled(False)
        self.pb_stop_rec.setObjectName(_fromUtf8("pb_stop_rec"))
        self.verticalLayout_2.addWidget(self.pb_stop_rec)
        self.pb_process_data = QtGui.QPushButton(self.f_buttons)
        self.pb_process_data.setEnabled(False)
        self.pb_process_data.setObjectName(_fromUtf8("pb_process_data"))
        self.verticalLayout_2.addWidget(self.pb_process_data)
        self.pb_sync_server = QtGui.QPushButton(self.f_buttons)
        self.pb_sync_server.setEnabled(False)
        self.pb_sync_server.setObjectName(_fromUtf8("pb_sync_server"))
        self.verticalLayout_2.addWidget(self.pb_sync_server)
        self.pb_open_rec_folder = QtGui.QPushButton(self.f_buttons)
        self.pb_open_rec_folder.setEnabled(False)
        self.pb_open_rec_folder.setObjectName(_fromUtf8("pb_open_rec_folder"))
        self.verticalLayout_2.addWidget(self.pb_open_rec_folder)
        self.horizontalLayout_2.addWidget(self.f_buttons)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Open Ephys Recording Manager", None))
        self.label_2.setText(_translate("MainWindow", "Experimenter Name", None))
        self.pb_experimenter.setText(_translate("MainWindow", "Options", None))
        self.pt_experimenter.setPlainText(_translate("MainWindow", "sander", None))
        self.label_3.setText(_translate("MainWindow", "Root Folder", None))
        self.pb_root_folder.setText(_translate("MainWindow", "Browse", None))
        self.label_4.setText(_translate("MainWindow", "Animal ID", None))
        self.pb_animal.setText(_translate("MainWindow", "Options", None))
        self.label_5.setText(_translate("MainWindow", "Experiment ID", None))
        self.pb_experiment_id.setText(_translate("MainWindow", "Options", None))
        self.label_10.setText(_translate("MainWindow", "Arena size(cm)", None))
        self.label_11.setText(_translate("MainWindow", "X (width):", None))
        self.pt_arena_size_x.setPlainText(_translate("MainWindow", "175", None))
        self.label_12.setText(_translate("MainWindow", "Y (height):", None))
        self.pt_arena_size_y.setPlainText(_translate("MainWindow", "175", None))
        self.label_6.setText(_translate("MainWindow", "Channel mapping", None))
        self.pt_chan_map_1.setPlainText(_translate("MainWindow", "CA1", None))
        self.pt_chan_map_1_chans.setPlainText(_translate("MainWindow", "1-64", None))
        self.pt_chan_map_2.setPlainText(_translate("MainWindow", "MEC", None))
        self.pt_chan_map_2_chans.setPlainText(_translate("MainWindow", "65-128", None))
        self.label_7.setText(_translate("MainWindow", "Bad Channels", None))
        self.pb_load_last.setText(_translate("MainWindow", "Load Last Settings", None))
        self.pb_load.setText(_translate("MainWindow", "Load Settings", None))
        self.pb_save.setText(_translate("MainWindow", "Save Settings", None))
        self.pb_cam_set.setText(_translate("MainWindow", "Camera Settings", None))
        self.pb_task_set.setText(_translate("MainWindow", "Task Settings", None))
        self.pb_test_devices.setText(_translate("MainWindow", "Test Devices", None))
        self.label.setText(_translate("MainWindow", "Current Recording File:", None))
        self.label_8.setText(_translate("MainWindow", "Tracking:", None))
        self.rb_tracking_yes.setText(_translate("MainWindow", "Yes", None))
        self.rb_tracking_no.setText(_translate("MainWindow", "No", None))
        self.label_9.setText(_translate("MainWindow", "Task Active:", None))
        self.rb_task_yes.setText(_translate("MainWindow", "Yes", None))
        self.rb_task_no.setText(_translate("MainWindow", "No", None))
        self.pb_start_rec.setText(_translate("MainWindow", "Start Recording", None))
        self.pb_stop_rec.setText(_translate("MainWindow", "Stop Recording", None))
        self.pb_process_data.setText(_translate("MainWindow", "Process Data", None))
        self.pb_sync_server.setText(_translate("MainWindow", "Synch with QNAP", None))
        self.pb_open_rec_folder.setText(_translate("MainWindow", "Open Recording Folder", None))

